name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Apache
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2

    - name: Copy HTML file to Apache directory
      run: |
        sudo cp ./workflows/index.html /var/www/html/

    - name: Restart Apache
      run: |
        sudo systemctl restart apache2
